### PR TITLE
add allero to the landscape

### PR DESCRIPTION
**Pull request by idanshahar**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Does it follow the guidelines for [new entries](https://github.com/cdfoundation/cdf-landscape#new-entries)?
* [x] Have you added an SVG to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow logo [guidelines](https://github.com/cdfoundation/cdf-landscape#logos)?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~5 minutes after opening the pull request, the CNCF-Bot will post a link for you to preview your changes. Have you confirmed that they are correct and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by MarckK** [comment]
Thank you for your PR, @idanshahar!

This relates to the [suggestion by @sbtaylor15 that we should have a Policy Category](https://github.com/cdfoundation/cdf-landscape/issues/199).

I'd like to have wider feedback on creating this new category and move forward with it!

**Comment by idanshahar** [comment]
> 

Thank you @MarckK, policies for CI/CD are getting more and more popular, many companies developed in-house policy enforcement for their CI/CD, and there are several security companies enforcing security practices in CI/CD as well. I believe pipeline governance definitely deserves a new category in CDF :)

**Comment by MarckK** [comment]
Hi @idanshahar, 

Thank you for providing more context on the growth in pipeline policy tools on https://github.com/cdfoundation/cdf-landscape/issues/199.

What do you think about renaming the proposed new sub-category to "Policy" and moving it to within the "DevSecOps" main category?

**Comment by idanshahar** [comment]
Hey @MarckK 
Sure thing, done!

**Comment by MarckK** [comment]
Looks awesome, @idanshahar!

Thank you for this PR!

I'm sorry for my slow response -- I was off all of last week and didn't see your changes until today. Apologies for the delay!

**Pull request merged**
