### PR TITLE
Add SCM Category for issue #16

### PR DESCRIPTION
**Pull request by sbtaylor15**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [X] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [X] Have you picked the single best (existing) category for your project?
* [X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [X] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [X] Does your project/product name match the text on the logo?
* [X] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [X] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by sbtaylor15** [comment]
Added commit to include new QR positioning

**Comment by sbtaylor15** [comment]
LGTM

**Comment by caniszczyk** [comment]
This is a great start, need to add GitLab, Bitbucket etc ;)

**Comment by TracyRagan** [comment]
I'm hoping that companies will self add. I don't have their logos. I did not add GitLab to SCM because they are in CD Pipeline, and right now it looks like you can only be in one category.

**Comment by dankohn** [comment]
Here's the BitBucket logo: https://d301sr5gafysq2.cloudfront.net/4a68d65c1182/img/logos/bitbucket/bitbucket-attribution-blue.svg. You can find it by searching for https://www.google.com/search?q=grpc+logo&tbs=ift:svg,imgo:1&tbm=isch but with bitbucket logo in place of grpc.

I recommend disallowing the same item from appearing in more than one box, as it will cause the number of logos on your landscape to multiply exponentially.

For GitLab, you can put GitLab Runner as their CI platform:
https://github.com/cncf/landscape/blob/95e713633968611219c9ac76140e06b185752269/hosted_logos/gitlab-runner.svg
https://github.com/gitlabhq/gitlab-runner

**Pull request merged**
