### PR TITLE
Add Eiffel

### PR DESCRIPTION
**Pull request by e-backmark-ericsson**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
_Our project does not have 300 GitHub stars_
* [x] Have you picked the single best (existing) category for your project?
_I propose to add a new category as I don't think there is a single existing category where Eiffel fits. The proposed 'CI/CD Protocols' category could potentially also hold entries for AI/ML protocols. An option could be to put it in a new sub category 'Messaging' under 'CI & Pipeline Orchestration'_
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?
_I haven't seen that staging server link yet. Is there any problem creating it?_

### CODE REVIEW

**Comment by e-backmark-ericsson** [comment]
@AndreyKozlov1984, @danlopez00 - Do you have any idea on why the CNCF Bot did not post a URL to the staging server for this PR?

**Comment by danlopez00** [comment]
I think it needs a Crunchbase entry and native svg logos.

**Comment by e-backmark-ericsson** [comment]
It has a native svg logo, as far as I can tell at least. But no Crunchbase entry. I had hoped that was not a must. I'm confused that it seems that Netlify did not even try to build it, so no error log is to be found,. At least there is no trace of it here: https://app.netlify.com/sites/cdf-landscape/deploys
As the Netlify bot says 'pending reviews' above, sounds a bit like someone should review it and _then_ Netlify can build a preview. Could that be it?
Anyway, I'll put LGTM anyway now and see what happens.

**Comment by e-backmark-ericsson** [comment]
LGTM

**Comment by e-backmark-ericsson** [comment]
Added a Crunchbase entry for Eiffel. Also ticked all checkboxes in the PR (leaving comments on the ones not applicable) assuming that could trigger the deployment onto the staging server.

**Comment by e-backmark-ericsson** [comment]
LGTM

**Comment by e-backmark-ericsson** [comment]
@danlopez00, could this be reviewed now or is something more needed?

**Pull request merged**
