### PR TITLE
Add Cycloid

### PR DESCRIPTION
**Pull request by sbtaylor15**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [X ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ X] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ X] Have you picked the single best (existing) category for your project?
* [ X] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [ X] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ X] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [ X] Does your project/product name match the text on the logo?
* [X ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ X] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by sbtaylor15** [comment]
LGTM

**Comment by dankohn** [comment]
For Jira, you want to use a logo with the name in it.

Here you go: https://wac-cdn.atlassian.com/dam/jcr:e348b562-4152-4cdc-8a55-3d297e509cc8/Jira%20Software-blue.svg?cdnVersion=614

**Comment by dankohn** [comment]
@sbtaylor15 If you create an account on slack.cncf.io and ping me, I can help you debug some of the issues you're having. FYI, you generally don't want to use `rebase` here but can instead `git merge origin/master` if you want to ensure that your branch includes all changes from master.

Also, going forward, you want to make your changes on a branch of your fork, rather than on `master`.

**Comment by dankohn** [comment]
Your Selenium logo has a white rather than transparent background and is missing the project name. Here's a corrected one, or I can replace it after you merge.
[selenium.svg.zip](https://github.com/cdfoundation/cdf-landscape/files/3702771/selenium.svg.zip)

**Comment by sbtaylor15** [comment]
@dankohn I think we got this finally sorted out.  Additional changed needed to be made due to a failed build on the PR.  Lets finish this PR and get it published before applying the selenium logo.

What do we need to do to get the build to run for this PR?

**Comment by dankohn** [comment]
It's running. https://app.netlify.com/sites/cdf-landscape/deploys/5d9c962f08a70d0008ade991

You can see it's results on #cdf-logs on the CNCF Slack.

**Pull request merged**
