### PR TITLE
Change placement of end user member category

### PR DESCRIPTION
**Pull request by MarckK**
### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Does it follow the guidelines for [new entries](https://github.com/cdfoundation/cdf-landscape#new-entries)?
* [ ] Have you added an SVG to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow logo [guidelines](https://github.com/cdfoundation/cdf-landscape#logos)?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post a link for you to preview your changes. Have you confirmed that they are correct and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by MarckK** [comment]
As requested by @tracymiranda 👍

**Review by markyjackson-taulia — APPROVED** [review]
I won't merge pending @tracymiranda review.

**Comment by MarckK** [comment]
LGTM.

Let us know what you think, @tracymiranda

**Comment by tracymiranda** [comment]
+ LGTM and we will be pulling these cards onto cd.foundation main website and needed the card mode changed, so this works beautifully for that!

**Pull request merged**
