### PR TITLE
Adding Drone CI to the Landscape

### PR DESCRIPTION
**Pull request by tiffanyjachja**
Looking to add Drone CI as a Continuous Integration solution for the CDF Landscape. Let me know if there are any issues or questions!

Repo Link: [https://github.com/drone/drone](https://github.com/drone/drone)

Thank you. 

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [ ] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [ ] Is your project closed source or, if it is open source, does your project have at least 300 GitHub stars?
* [ ] Have you picked the single best (existing) category for your project?
* [ ] Does it follow the other guidelines from the [new entries](https://github.com/cdfoundation/cdf-landscape#new-entries) section?
* [ ] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [ ] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cdfoundation/cdf-landscape#logos)?
* [ ] Does your project/product name match the text on the logo?
* [ ] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [ ] ~5 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by ravilach** [comment]
For the wise and all-knowing CDF, Drone is a separate project and all the sub-projects that come along with the Drone.io family. As a heads up, Cloudbees, Jenkins, and JenkinX all have coverage on the first line. 
image

**Comment by markyjackson-taulia** [comment]
> For the wise and all-knowing CDF, Drone is a separate project and all the sub-projects that come along with the Drone.io family. As a heads up, Cloudbees, Jenkins, and JenkinX all have coverage on the first line.
> image

right but will drone.io continue to be sperate in terms of branding and Cloudbees, Jenkins and jx have. That is my only question.

**Comment by ravilach** [comment]
We are taking the lead on the project like Cloudbees to JenkinsX and Jenkins.

**Comment by tiffanyjachja** [comment]
Hey Marky, short-form answer: "Drone will always remain open-source, and Harness will invest significantly over the coming years to its community, platform, and mission. Harness will also contribute several internal projects later this year to the open-source community."

Details here:
https://harness.io/2020/08/harness-acquires-ci-pioneer-drone-io-and-commits-to-open-source/

**Comment by markyjackson-taulia** [comment]
Thank you @tiffanyjachja

**Pull request merged**
